### ISSUE TITLE
Do not work on nested resource ?

### ISSUE THREAD

**Issue by mnek84** [davejamesmiller/laravel-breadcrumbs#118]
i have a nested resource like  event.product  and if a register the index for product i don't receive the event parameter. there is a way to configure that?

**Comment by davejamesmiller** [comment]
Should work as far as I know. If you need help making it work I need more information:

https://github.com/davejamesmiller/laravel-breadcrumbs#support-requests--bug-reports

**Comment by judgej** [comment]
Works for me on four-level nested resources. The routes and stuff do get pretty hairy though, and can be difficult to manage, so it is easy to make a mistake that gives you a dead site.

Using route-model binding does help an awful lot to simplify things.

**Comment by lukedanielson** [comment]
Can nested resources be used with breadcrumbs without route-model binding?  I have a nested resource `admin.customers.jobs.show`, that requires the customer and job models, but for some reason the customer parameter passed to the `Breadcrumbs::register('admin.customers.show')` changes from a model to an integer when trying to load the customer's job view.

In the `admin.customers.show` controller method, and all controller methods for that matter, I am using `Breadcrumbs::setCurrentRoute` to set the proper route and pass the proper parameters.  In this specific route I am passing a customer model, as it load correctly on the `admin.customers.show` view.  Does it change to an integer because that controller method isn't run here?  Yet it is grabbing the proper id.

**Comment by judgej** [comment]
It works find for me - I get the object in all cases.

Have you checked that the name of the model in your URL is correct? It should be "customers" (with an "s") even in a route for which you are accessing just one customer.

That's my initial thought, but I suspect I'm missing something that a bit more code my show us.

**Comment by davejamesmiller** [comment]
@lukedanielson If you use route model binding, it will receive exactly what the controller does, and if you don't use route model binding, it will receive whatever you pass it in the view or from the child breadcrumb. If you need any further help, please open a new issue and provide all the required debugging information as linked above.
