### ISSUE TITLE
TestCase.php in 3.0.x

### ISSUE THREAD

**Issue by ADRDev** [davejamesmiller/laravel-breadcrumbs#141]
Could you rename the file/class or namespace it? Having it the the global namespace forced me to rename my own TestCase.php to something else to avoid the conflict.

**Comment by davejamesmiller** [comment]
> Could you rename the file/class or namespace it?

Already done in [4.x-dev](https://github.com/davejamesmiller/laravel-breadcrumbs/blob/4.x/tests/TestCase.php), but no I'm not backporting it.

> Having it the the global namespace forced me to rename my own TestCase.php to something else to avoid the conflict.

In PHP / PHPUnit it shouldn't conflict because it's not listed composer.json so won't be picked up by the autoloader.

If your IDE is the problem, you can probably tell it to ignore the directory if it's annoying you.

**Comment by ADRDev** [comment]
Oh, duh! Sorry. I half expected there was a simple solution I was overlooking. Sorry about that!
