### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by mdasiff007** [davejamesmiller/laravel-breadcrumbs#154]
I am working Laravel 5.5, php version 7.0.10, while run this command 
composer require davejamesmiller/laravel-breadcrumbs, 
I'm getting this issue. Kindly Check Attached Screen Shot.
![capture](https://user-images.githubusercontent.com/13522908/33072884-2590592e-cee7-11e7-8809-d669d5a5b93b.PNG)

**Comment by mdasiff007** [comment]
By the way, I'm new Laravel.

**Comment by davejamesmiller** [comment]
The screenshot shows you're using Laravel 5.4 not 5.5.

**Comment by mdasiff007** [comment]
Thanx for your reply, Yes I'm using 5.4, and running this command 
### composer require davejamesmiller/laravel-breadcrumbs 
but I'm getting that error which is attached with screenshot. can you resolve this. I'm new to laravel.

**Comment by davejamesmiller** [comment]
I guess you need to tell Composer to install the old version (3.x) since it's defaulting to the latest.

https://stackoverflow.com/questions/40914114/install-specific-version-of-package-using-composer

**Comment by mdasiff007** [comment]
_I'm sorry, I can't get you. Let me show in brief. It's my humble request please solve my problem_
------------------------------------------------------
I wanna setup breadcrumb with this command **composer require davejamesmiller/laravel-breadcrumbs**
Configuration: 
**Laravel:** 5.4
**PHP:** 7.0.10
**composer.json**
{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=5.6.4",
        "laravel/framework": "5.4.*",
        "laravel/tinker": "~1.0"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~5.7"
    },
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
        "post-root-package-install": [
            "php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ],
        "post-install-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postInstall",
            "php artisan optimize"
        ],
        "post-update-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postUpdate",
            "php artisan optimize"
        ]
    },
    "config": {
        "preferred-install": "dist",
        "sort-packages": true,
        "optimize-autoloader": true
    }
}
//Error after run your command
![capture](https://user-images.githubusercontent.com/13522908/33185036-faae7310-d0a5-11e7-93cb-b7e96cfb0f89.JPG)

Kindly check whats going wrong. Is my composer is outdated or your breadcrumbs file is outdated? Actually, I'm totally confused.
Thankyou.

**Comment by davejamesmiller** [comment]
Sorry I'm not going to teach you to use Composer. Try the Laravel forums or
Stack Overflow if you need help.

On 23 Nov 2017 6:00 pm, "Md Asif" <notifications@github.com> wrote:

*I'm sorry, I can't get you. Let me show in brief. It's my humble request
please solve my problem*

I wanna setup breadcrumb with this command *composer require
davejamesmiller/laravel-breadcrumbs*
Configuration:
*Laravel:* 5.4
*PHP:* 7.0.10
*composer.json*
{
"name": "laravel/laravel",
"description": "The Laravel Framework.",
"keywords": ["framework", "laravel"],
"license": "MIT",
"type": "project",
"require": {
"php": ">=5.6.4",
"laravel/framework": "5.4.




*", "laravel/tinker": "~1.0" }, "require-dev": { "fzaninotto/faker":
"~1.4", "mockery/mockery": "0.9.*",
"phpunit/phpunit": "~5.7"
},
"autoload": {
"classmap": [
"database"
],
"psr-4": {
"App\": "app/"
}
},
"autoload-dev": {
"psr-4": {
"Tests\": "tests/"
}
},
"scripts": {
"post-root-package-install": [
"php -r "file_exists('.env') || copy('.env.example', '.env');""
],
"post-create-project-cmd": [
"php artisan key:generate"
],
"post-install-cmd": [
"Illuminate\Foundation\ComposerScripts::postInstall",
"php artisan optimize"
],
"post-update-cmd": [
"Illuminate\Foundation\ComposerScripts::postUpdate",
"php artisan optimize"
]
},
"config": {
"preferred-install": "dist",
"sort-packages": true,
"optimize-autoloader": true
}
}
//Error after run your command
[image: capture]
<https://user-images.githubusercontent.com/13522908/33185036-faae7310-d0a5-11e7-93cb-b7e96cfb0f89.JPG>

Kindly check whats going wrong. Is my composer is outdated or your
breadcrumbs file is outdated? Actually, I'm totally confused.
Thankyou.

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/davejamesmiller/laravel-breadcrumbs/issues/154#issuecomment-346676170>,
or mute the thread

**Comment by mdasiff007** [comment]
Thankyou for your cooperation. I resolved this issue.
