### ISSUE TITLE
Json response

### ISSUE THREAD

**Issue by atoropin** [davejamesmiller/laravel-breadcrumbs#161]
Hello!

Please, tell me, how can I get a json response with breadcrumbs, instead of rendering blade templates?

Thank you in advance.

**Comment by davejamesmiller** [comment]
Either use the breadcrumbs::json-ld template or make your own.

On 22 Jan 2018 08:05, "Andrey Toropin" <notifications@github.com> wrote:

Hello!

Please, tell me, how can I get a json response with breadcrumbs, instead of
rendering blade templates?

Thank you in advance.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/davejamesmiller/laravel-breadcrumbs/issues/161>, or mute
the thread
