### ISSUE TITLE
Feature Request: Be able to pass the register name to the call back function

### ISSUE THREAD

**Issue by it-stalwartjourneys** [davejamesmiller/laravel-breadcrumbs#176]
Something like:

```
Breadcrumbs::register('home', function ($breadcrumbs, $name) {
    $breadcrumbs->push('Home', $name);
});
```

Perhaps adding it as the default, so that ultimately we could do something like`Breadcrumbs::register('home', Home')` that would  be equivalent to the above.

**Comment by davejamesmiller** [comment]
I think what you're suggesting is to remove some duplication (the route name). You would still need to call `route()` though. So the example from the documentation would become:

```php
// Home
Breadcrumbs::register('home', function ($breadcrumbs, $name) {
    $breadcrumbs->push('Home', route($name));
});

// Home > About
Breadcrumbs::register('about', function ($breadcrumbs, $name) {
    $breadcrumbs->parent('home');
    $breadcrumbs->push('About', route($name));
});

// Home > Blog
Breadcrumbs::register('blog', function ($breadcrumbs, $name) {
    $breadcrumbs->parent('home');
    $breadcrumbs->push('Blog', route($name));
});

// Home > Blog > [Category]
Breadcrumbs::register('category', function ($breadcrumbs, $name, $category) {
    $breadcrumbs->parent('blog');
    $breadcrumbs->push($category->title, route($name, $category->id));
});

// Home > Blog > [Category] > [Post]
Breadcrumbs::register('post', function ($breadcrumbs, $name, $post) {
    $breadcrumbs->parent('category', $post->category);
    $breadcrumbs->push($post->title, route($name, $post));
});
```

However, I don't find that as easy to read/understand - I prefer to keep it explicit.

It's also not backwards-compatible, so if I did change it everyone would have to update their code, or I would have to add a different function or another config option. I don't think it's worth that complexity.

So I don't think I'm going to change anything, at least for now.

Now if you still want to do this in your own code, you could just use a [macro](https://github.com/davejamesmiller/laravel-breadcrumbs#macros) - e.g. (this is untested):

```php
Breadcrumbs::macro('add', function($name, $callback) {
    Breadcrumbs::register($name, function($breadcrumbs, ...$args) use ($name, $callback) {
        $callback($breadcrumbs, $name, ...$args);
    });
});

Breadcrumbs::add('home', function ($breadcrumbs, $name) {
    $breadcrumbs->push('Home', route($name));
});
```

Adjust as necessary for your particular use case.

As for the second suggestion (`Breadcrumbs::register('home', Home')`) - I think that would only work for breadcrumbs with no parent, so it has very limited use (in most cases just the homepage). And again I prefer for code to be explicit / consistent, rather than having multiple ways to do the same thing.

But as above you can make a macro for it if you want:

```php
Breadcrumbs::macro('simple', function($name, $title) {
    Breadcrumbs::register($name, function() use ($name, $title) {
        $breadcrumbs->push($title, route($name));
    });
});

Breadcrumbs::simple('home', 'Home');
```
